const nodemailer = require("nodemailer");

function sendEmail({
                       song_name,
                       artist,
                       youtube_title,
                       youtube_views,
                       spotify_title,
                       spotify_streams,
                       shazam_count,
                       chartex_stats,
                       spotontrack_image_url,
                       mediaforest_image_url,
                       tiktok_csv_url
                   }) {
    const transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {
            user: process.env.MAIL_USER,
            pass: process.env.MAIL_PASS
        }
    });

    const html = `
    <div style="font-family: Arial; padding: 20px;">
      <h2 style="color:#4a90e2;">🎵 Track Analysis Report</h2>
      <p><strong>Song:</strong> ${song_name}<br/>
         <strong>Artist:</strong> ${artist}</p>

      <h3>🎧 DSP Performance</h3>
      <p><strong>YouTube:</strong><br/>${youtube_title}<br/>${youtube_views}</p>
      <p><strong>Spotify:</strong><br/>${spotify_title}<br/>${spotify_streams}</p>
      <p><strong>Shazam:</strong> ${shazam_count}</p>
      <p><strong>Spotontrack:</strong>
      <img src="data:image/png;base64,${spotontrack_image_base64}" style="max-width:600px; border-radius: 8px;" />

      <h3>📱 TikTok Performance</h3>
      <p>${chartex_stats}</p>
      <a href="data:text/csv;base64,${tiktok_csv_base64}" download="TikTokPerformance.csv" style="display:inline-block;margin-top:8px;padding:8px 16px;background:#4a90e2;color:white;border-radius:6px;text-decoration:none;">
            Download TikTok CSV
      </a>


      <h3>📻 Radio Performance</h3>
      <img src="data:image/png;base64,${mediaforest_image_base64}" style="max-width:600px; border-radius: 8px;" />

      <p style="margin-top:30px;color:#999;font-size:12px;">Generated by SongScape AI</p>
    </div>
  `;

    return transporter.sendMail({
        from: `"SongScape AI" <${process.env.MAIL_USER}>`,
        to: process.env.MAIL_TO,
        subject: `${song_name} Analysis Report`,
        html
    });
}

module.exports = { sendEmail };
